languageCode = "en-gb"
title = "BookStack"
baseurl = "https://bookstackapp.com/"
theme="bookstack"
enableGitInfo=true

[permalinks]
  post = "/blog/:slug/"

[params]
  blogCover = "/images/cover.jpg"
  googleAnalyticsUserID = "UA-61486258-4"
